import { Generic } from './generic';
import { Language } from './language';
import { PartnerAdminCookies } from './partnerAdminCookies';
import { suiteService } from './suiteService';
export class Partner {
    id: number;
    lan: string;
    faviconId: number;
    code: string;
    name: string;
    subdomain: string;
    domain: string;
    bgColor: string;
    bgColorL: string;
    foreColor: string;
    foreColorL: string;
    footBgColor: string;
    borderColor: string;
    color: string;
    gradColor: string;
    logoPath: string;
    faviconPath: string;
    terms: string;
    creation: string;
    active: boolean;
    loginText: string;
    randomPassword: boolean;
    welcomeEmail: boolean;
    externalUrl: string;
    apiKey: string;
    phone: string;
    email: string;
    jiraX3: string;
    jiraFoot: string;
    tokenExpiration:number;
    banner: string;
    cabecera: string;
    separador: string;
    pie: string;
    logotipo: string;
    favicon: string;
    preloader: string;
    whatsapp: string;
    includePhone: boolean;
    includeWhatsapp: boolean;
    includeEmail: boolean;
    includeC2C: boolean;
    includeCallMeBack: boolean;
    c2CNumber: string;
    show: number;
    loginType: number;
    loginTypeText:string;
    login: string;
    languageId : number;
    title : string;
    subtitle : string;
    description : string;
    additionaltext : string;
    uniqueIdentifier : string;
    userPlaceholder : string;
    loginTitle: string;
    loginSubtitle: string;
    communicationsTitle: string;
    suiteId : number;
    applyToAllSuites : boolean;
    html : string;
    javascript : string;
    chatId : string;
    welcome : string;
    pathFileLookFeelCss:string;
    showFileLookFeelCss:boolean;
    webPathFileLookFeelCss:string;
    suiteName : string;
    suiteDesc : string;
    suiteIcon : string;
    partnerSuites: Generic[];
    suiteServices: suiteService[];
    googleAnyliticsId : string;
    emailSenderId:number;
    customDomain:string;
    serviceTitle : string;
    serviceTitleDescription : string;
    welcomeGeneralEnable:boolean;
    welcomeCustomEnable:boolean;
    welcomeHtmlEnable:boolean;
    welcomeHtmlBody:string;
    welcomeCustomBody:string;
    welcomeHtmlTo:string;
    preactivationEnable:boolean;
    partnerURL:string;
    emailSenderFromName:string;
    sendFromHour: string;
    seoTitle:string;
    seoDescription:string;
    seoImage:string;
    keepSession: boolean;
    includeFooter: boolean;
    footerHtml:string;
    rememberOneEnable:boolean;
    rememberOneSubject:string;
    rememberOneDays:number;
    rememberOneHtml:string;
    rememberTwoEnable:boolean;
    rememberTwoSubject:string;
    rememberTwoDays:number;
    rememberTwoHtml:string;
    cookiesPolicyLink: string;
    privacyPolicyLink: string;
    partnerCookies:PartnerAdminCookies;
    hasFullProfile: boolean;
    languages: Language[];
}
